language: php

dist: xenial
php:
  - "7.1"

env:
  - OXID=6.0
  - OXID=6.1
  - OXID=6.2

jobs:
  allow_failures:
    - env: OXID=6.2

cache:
  directories:
  - $HOME/OXID
services: mysql

before_install:
  - echo 'Europe/Berlin' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - mysql -e 'CREATE DATABASE oxid;'

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - composer install
  - vendor/bin/phpcs --standard=PSR12 --extensions=php --ignore=vendor .
  - vendor/bin/install-oxid

script:
  - cd ~/OXID/
#  - ./vendor/bin/runtests-coverage
  - ./vendor/bin/runtests
#  - php vendor/bin/codacycoverage clover ~/OXID/source/modules/oxcom/moduleinternals/Tests/reports/clover.xml --git-commit=$TRAVIS_COMMIT

before_cache:
  - composer remove "oxid-community/moduleinternals"
  - rm -rf ~/OXID/source/modules/oxcom/moduleinternals
  - rm -rf ~/OXID/vendor/oxid-community/moduleinternals
  - rm -rf ~/OXID/source/tmp/*

