name: oxid module tests

on: [push]

jobs:

  build:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oxid
        ports: 
          - 3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    runs-on: ubuntu-latest
    container: keywanghadamioxid/oxid-test:6.1
    env:
      MODULE_NAME: moduleinternals
    steps:
    - uses: actions/checkout@v1
        
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: setup oxid
      run: bash /var/www/OXID/setup.sh

    - name: runt tests
      run: |
        cd /var/www/OXID/
        vendor/bin/runtests
